#This is an example of Makefile

PROGRAM = dpsd
ARCH    = i686
OS      = linux

#header directory
INCDIRS += .
INCDIRS += ../../

#source directory
SRCDIRS += .
SRCDIRS += ../../

include /home/eyonggu/github/commk/Common.mk
