#This is an example of Makefile

PROGRAM = dpssh
ARCH    = i686
OS      = linux

#header directory
INCDIRS += 
INCDIRS += ../../
INCDIRS += /home/eyonggu/include

#source directory
SRCDIRS += .
SRCDIRS += ../../

LIBDIRS += /home/eyonggu/lib

LDLIBS += edit

include /home/eyonggu/github/commk/Common.mk
